"use strict";

export const canvasBackground = document.getElementById("canvas-bg");
export const contextBackground = canvasBackground.getContext("2d");
export const canvasAnim = document.getElementById("canvas-anim");
export const contextAnim = canvasAnim.getContext("2d");
export const scoreDigital = document.getElementById("score-digits");
export const ghostIcon = document.getElementById("ghost-icon");
export const title = document.getElementById("title");
export const result = document.getElementById("result");
export const menu = document.getElementById("menu");
export const start = document.getElementById("start");
export const progress = document.getElementById("progress");
export const wrapper = document.getElementById("wrapper-game");
export const fullscreenButton = document.getElementById("fullscreen-button");
export const questionMark = document.getElementById("question-mark-button");
export const instruction = document.getElementById("instruction");
export const arrows = document.getElementById("arrows");
export const arrowLeft = document.getElementById("arrow-left");
export const arrowUp = document.getElementById("arrow-up");
export const arrowDown = document.getElementById("arrow-down");
export const arrowRight = document.getElementById("arrow-right");
